// Code generated by github.com/stokelp/go-jsonschema, DO NOT EDIT.

package test

type Thing struct {
	// S corresponds to the JSON schema field "s".
	S *string `json:"s,omitempty" yaml:"s,omitempty" mapstructure:"s,omitempty"`
}
