// Code generated by github.com/stokelp/go-jsonschema, DO NOT EDIT.

package test

type RefToMap struct {
	// MyThing corresponds to the JSON schema field "myThing".
	MyThing map[string]float64 `json:"myThing,omitempty" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`
}
